name: "Build"
on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubicloud-standard-2
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Build front end
        run: |
          npm ci
          npm run build

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        if: github.event_name != 'pull_request'
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "luzmo-iq-playground.luzmo.com"
          source_dir: "dist/"
          destination_dir: ""

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        if: github.event_name != 'pull_request'
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
